# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import streamlit as st
from streamlit.logger import get_logger
import random

LOGGER = get_logger(__name__)


def run():
    st.set_page_config(
        page_title="Hello",
        page_icon="👋",
    )
    insult = random.choice([
    "dumb",
    "slow",
    "simple",
    "thick",
    "idiotic",
    "foolish",
    "dull",
    "ignorant",
    "dense",
    "silly",
    "unintelligent",
    "dopey",
    "fatuous",
    "obtuse",
    "irrational",
    "insane",
    "mad",
    "soft",
    "unreasonable",
    "doltish",
    "boneheaded",
    "brain-dead",
    "vacuous",
    "thickheaded",
    "mindless",
    "brainless",
    "witless",
    "lamebrain",
    "bonehead",
    "dorky",
    "crazy",
    "senseless",
    "dunderheaded",
    "opaque",
    "dim",
    "pinheaded",
    "oafish",
    "weak-minded",
    "dopy",
    "idiotical",
    "moronic",
    "lamebrained",
    "softheaded",
    "dim-witted",
    "empty-headed",
    "gormless",
    "unsmart",
    "looney",
    "absurd",
    "knuckleheaded",
    "airheaded",
    "chuckleheaded",
    "slow-witted",
    "half-witted",
    "lunatic",
    "lunkheaded",
    "bubbleheaded",
    "thick-witted",
    "fool",
    "imbecile",
    "imbecilic",
    "birdbrained",
    "feebleminded",
    "simpleminded",
    "cretinous",
    "uneducated",
    "uninformed",
    "asinine",
    "unthinking",
    "illiterate",
    "illogical",
    "nonsensical",
    "unintellectual",
    "daft",
    "unwise",
    "whacky",
    "invalid",
    "zany",
    "cuckoo",
    "lowbrow",
    "wacky",
    "untaught",
    "preposterous",
    "loony",
    "dippy",
    "nutty",
    "sappy",
    "fallacious",
    "kooky",
    "harebrained",
    "daffy",
    "screwball",
    "dotty",
    "crackpot",
    "boobish",
    "cockeyed",
    "half-baked",
    "tomfool",
    "balmy",
    "kookie",
    "featherheaded",
    "idiot",
    "moron",
    "lunatic",
    "dummy",
    "fool",
    "loser",
    "prat",
    "imbecile",
    "numbskull",
    "dolt",
    "know-nothing",
    "mutt",
    "dimwit",
    "ignoramus",
    "natural",
    "bonehead",
    "dullard",
    "jackass",
    "donkey",
    "dumbhead",
    "dunderhead",
    "simpleton",
    "blockhead",
    "dunce",
    "knucklehead",
    "goof",
    "doofus",
    "dope",
    "chucklehead",
    "ninny",
    "dumb cluck",
    "jerk",
    "airhead",
    "lunkhead",
    "goon",
    "pinhead",
    "nitwit",
    "numskull",
    "dork",
    "hardhead",
    "lamebrain",
    "stupe",
    "cretin",
    "oaf",
    "dummkopf",
    "loon",
    "bubblehead",
    "dum-dum",
    "clown",
    "nimrod",
    "cluck",
    "golem",
    "meathead",
    "yahoo",
    "noddy",
    "turkey",
    "clunk",
    "schnook",
    "dip",
    "deadhead",
    "dodo",
    "ninnyhammer",
    "schlub",
    "hammerhead",
    "nincompoop",
    "thickhead",
    "chowderhead",
    "fathead",
    "dumbbell",
    "birdbrain",
    "shlub",
    "lump",
    "clodpole",
    "half-wit",
    "villain",
    "noodle",
    "goose",
    "saphead",
    "nit",
    "gander",
    "ratbag",
    "cuddie",
    "mome",
    "buffoon",
    "dim bulb",
    "stock",
    "loggerhead",
    "cuddy",
    "woodenhead",
    "clodpoll",
    "loony",
    "skunk",
    "madman",
    "zany",
    "clot",
    "booby",
    "yo-yo",
    "snake",
    "creep",
    "mug",
    "nut",
    "beast",
    "gawk",
    "boor",
    "scatterbrain",
    "stinker",
    "cad",
    "featherbrain",
    "heel",
    "cur",
    "churl"
  ])
    if st.button("click me"):
        st.write(insult)





if __name__ == "__main__":
    run()

